### PR TITLE
fix: #618 Add inputFieldDefTypes for declarativeWrappingPlugin

### LINKED ISSUE #618: Make it easier to evolve the schema in a backward compatible way
I have been experimenting with https://github.com/ef-eng/graphql-query-rewriter to allow schema breaking changes without breaking existing clients (a la stripe with the version in the header).
It would be nice if it was somewhat integrated in nexus with some type safety. Not sure how that would look like yet.

### PR DESCRIPTION
**Pull request by tgriesser**
Fixes #618

### CODE REVIEW

**Review by Weakky — APPROVED** [review]
Looks all good to me, especially with that integration test 💯

**Comment by Sytten** [comment]
Is there some documentation yet on that feature, it sounds awesome!

**Comment by tgriesser** [comment]
Not really a feature, just allows for defining typings specific to input object type fields similar to output object fields, which was needed for the `declarativeWrappingPlugin` to work without type errors.

**Comment by tgriesser** [comment]
I can add some docs for it though

**Comment by Sytten** [comment]
Yeah would be nice, I would like to write a plugin similar to the query rewriter for nexus if possible to have backward compatible schemas.

**Pull request merged**
